name: Build Style Dictionary on Tokens Change

on:
  push:
    paths:
      - 'tokens/tokens.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'  # Especifique a versão do Node.js que você precisa

      - name: Install Dependencies
        run: npm install

      - name: Delete Build Folder
        run: rm -rf build  # Remove a pasta "build"

      - name: Install Style Dictionary
        run: npm install style-dictionary  # Instala o Style Dictionary

      - name: Run Style Dictionary Build
        run: npx style-dictionary build  # Execute o comando do Style Dictionary

      - name: Run other necessary steps
        run: |
          # Aqui você pode adicionar outras etapas necessárias após a construção do Style Dictionary
