name: Build Style Dictionary on Tokens Change

on:
  push:
    paths:
      - 'tokens/tokens.json'
  pull_request:
    paths:
      - 'tokens/tokens.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node Dependencies
      run: npm install style-dictionary
    - name: Build Style Dictionary
      run: npm run build
    - name: Commit Generated style-dictionary
      id: "auto-commit-action"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update design tokens
        branch: main